version: "3.8"
services:
  db:
    build:
      context: ./infra/mysql
      args:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/mysql

  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    depends_on:
      - db

  web:
    image: nginx:1.20-alpine    # Docker Hubのnginx利用(Dockerfile不要)
    ports:
      - 8081:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    depends_on:
      - app

volumes:
  db-store: